interface Listing {
  id: string,
  name: string,
  room_type: string,
  listing_url: string,
  price: number,
  medium_url: string,
  review_scores_rating: number,
  xl_picture_url: string,
  smart_location: string,
  guests_included: number,
  bathrooms: number,
  bedrooms: number,
  beds: number,
  number_of_reviews: number,
  host_picture_url: string,
  host_name: string,
  host_since: string,
  description: string,
}